version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  catalog-service:
    build: ./services/catalog-service
    volumes:
      - ./dataset:/dataset:ro
      - catalog-data:/data
    environment:
      REDIS_URL: redis://redis:6379
      SEED_PATH: /dataset/catalog-seed.json
      DB_PATH: /data/catalog.db
      UPLOAD_DIR: /data/uploads
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET wajib diisi melalui .env}
      SERVICE_TOKEN: ${SERVICE_TOKEN:?SERVICE_TOKEN wajib diisi melalui .env}
      ORDER_URL: http://order-service:3002
    depends_on:
      redis:
        condition: service_healthy

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"
    environment:
      CATALOG_URL: http://catalog-service:3001
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET wajib diisi melalui .env}
      SERVICE_TOKEN: ${SERVICE_TOKEN:?SERVICE_TOKEN wajib diisi melalui .env}
      DB_PATH: /data/order.db
    volumes:
      - order-data:/data
    depends_on:
      - catalog-service
      - redis

  payment-service:
    build: ./services/payment-service
    ports:
      - "3003:3003"
    environment:
      REDIS_URL: redis://redis:6379
      ORDER_URL: http://order-service:3002
      DB_PATH: /data/payment.db
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET wajib diisi melalui .env}
      SERVICE_TOKEN: ${SERVICE_TOKEN:?SERVICE_TOKEN wajib diisi melalui .env}
    volumes:
      - payment-data:/data
    depends_on:
      - redis

  tracking-service:
    build: ./services/tracking-service
    ports:
      - "3004:3004"
    environment:
      REDIS_URL: redis://redis:6379
      DB_PATH: /data/tracking.db
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET wajib diisi melalui .env}
      SERVICE_TOKEN: ${SERVICE_TOKEN:?SERVICE_TOKEN wajib diisi melalui .env}
      ORDER_URL: http://order-service:3002
    volumes:
      - tracking-data:/data
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - catalog-service
      - order-service

volumes:
  catalog-data:
  order-data:
  payment-data:
  tracking-data:
