const express=require("express"),jwt=require("jsonwebtoken"),crypto=require("node:crypto");
const {createClient}=require("redis"); const {pool,ready}=require("./db");
const app=express(); app.use(express.json());
const SECRET=process.env.JWT_SECRET,SERVICE_TOKEN=process.env.SERVICE_TOKEN,ORDER_URL=process.env.ORDER_URL||"http://localhost:3002";
if(!SECRET||SECRET.length<32||!SERVICE_TOKEN||SERVICE_TOKEN.length<32)throw new Error("JWT_SECRET dan SERVICE_TOKEN minimal 32 karakter wajib diisi");
async function order(path,options={}){const r=await fetch(ORDER_URL+path,{...options,headers:{"Content-Type":"application/json","x-service-token":SERVICE_TOKEN,...options.headers},signal:AbortSignal.timeout(3000)});const b=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(b.error||"order-service gagal"),{status:r.status});return b}
async function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace(/^Bearer\s+/i,""),SECRET);await order("/internal/users/"+req.user.sub+"/access");next()}catch{res.status(401).json({error:"token tidak valid atau akun nonaktif"})}}
const admin=(req,res,next)=>req.user.roles?.includes("admin")?next():res.status(403).json({error:"khusus admin"});
let pub,sub;
async function publish(){const c=await pool.connect();try{await c.query("BEGIN");const {rows}=await c.query("SELECT * FROM outbox_events WHERE published_at IS NULL ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 50");for(const e of rows){if(pub?.isReady)await pub.publish(e.topic,JSON.stringify({...e.payload,eventId:e.id}));await c.query("UPDATE outbox_events SET published_at=now() WHERE id=$1",[e.id])}await c.query("COMMIT")}catch{await c.query("ROLLBACK")}finally{c.release()}}
async function releaseEscrow(event){if(!event.titipanId||!event.eventId)return;const c=await pool.connect();try{await c.query("BEGIN");if(!(await c.query("INSERT INTO processed_events(event_id) VALUES($1) ON CONFLICT DO NOTHING RETURNING event_id",[event.eventId])).rowCount){await c.query("ROLLBACK");return}const tx=(await c.query("UPDATE transactions SET status='dilepas',updated_at=now() WHERE titipan_id=$1 AND status='tertahan' RETURNING *",[event.titipanId])).rows[0];if(tx){await order("/internal/titipan/"+event.titipanId+"/status",{method:"PATCH",body:JSON.stringify({status:"selesai"})});await c.query("INSERT INTO outbox_events(id,topic,payload) VALUES($1,'payment.released',$2) ON CONFLICT DO NOTHING",[crypto.randomUUID(),JSON.stringify({titipanId:event.titipanId,transactionId:tx.id})])}await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");console.error(e)}finally{c.release()}}
ready.then(async()=>{if(process.env.REDIS_URL){pub=createClient({url:process.env.REDIS_URL});sub=pub.duplicate();await Promise.all([pub.connect(),sub.connect()]);await sub.subscribe("titipan.diterima",m=>releaseEscrow(JSON.parse(m)).catch(console.error));setInterval(publish,1000).unref()}}).catch(console.error);
app.post("/v1/payments",auth,async(req,res,next)=>{try{const t=await order("/internal/titipan/"+req.body.titipanId);if(+t.customer_id!==+req.user.sub)return res.status(403).json({error:"bukan pemilik titipan"});if(t.status!=="menunggu_pembayaran")return res.status(409).json({error:"titipan belum dapat dibayar"});if(+req.body.amount!==+t.total)return res.status(409).json({error:"jumlah pembayaran tidak sesuai"});const key=req.headers["idempotency-key"]||req.body.idempotencyKey;if(!key)return res.status(400).json({error:"Idempotency-Key wajib"});const c=await pool.connect();try{await c.query("BEGIN");let tx=(await c.query("SELECT * FROM transactions WHERE idempotency_key=$1",[key])).rows[0];if(!tx){tx=(await c.query("INSERT INTO transactions(titipan_id,customer_id,amount,method,idempotency_key) VALUES($1,$2,$3,$4,$5) RETURNING *",[t.id,req.user.sub,t.total,req.body.method||"simulasi",key])).rows[0];await order("/internal/titipan/"+t.id+"/status",{method:"PATCH",body:JSON.stringify({status:"dibayar"})});await c.query("INSERT INTO outbox_events(id,topic,payload) VALUES($1,'order.paid',$2)",[crypto.randomUUID(),JSON.stringify({titipanId:t.id,transactionId:tx.id})])}await c.query("COMMIT");res.status(201).json(tx)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}catch(e){next(e)}});
app.get("/v1/payments/:titipanId",auth,async(req,res)=>{const x=(await pool.query("SELECT * FROM transactions WHERE titipan_id=$1",[req.params.titipanId])).rows[0];if(!x)return res.status(404).json({error:"pembayaran tidak ditemukan"});if(+x.customer_id!==+req.user.sub&&!req.user.roles?.includes("admin"))return res.status(403).json({error:"akses ditolak"});res.json(x)});
app.get("/v1/admin/payments",auth,admin,async(_q,res)=>res.json({payments:(await pool.query("SELECT * FROM transactions ORDER BY id DESC LIMIT 200")).rows}));
app.get("/health",async(_q,res)=>{try{await ready;await pool.query("SELECT 1");res.json({status:"ok",service:"payment"})}catch{res.status(503).json({status:"error"})}});
app.use((e,_q,res,_n)=>res.status(e.status||500).json({error:e.message||"kesalahan internal"}));
if(require.main===module)ready.then(()=>app.listen(3003)); module.exports={app,ready,releaseEscrow};
