events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;

        # CORS untuk semua response
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Request-Id";

        # Handle preflight OPTIONS
        location / {
            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
                add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Request-Id";
                return 204;
            }
            return 404;
        }

        # catalog-service
        location /v1/items {
            proxy_pass http://catalog-service:3001;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
        }
        location /v1/toko {
            proxy_pass http://catalog-service:3001;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
        }

        # order-service
        location /v1/orders {
            proxy_pass http://order-service:3002;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
        }
        location /v1/catalog {
            proxy_pass http://order-service:3002;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
        }
        location /v1/login {
            proxy_pass http://order-service:3002;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
        }

        # payment-service
        location /v1/payments {
            proxy_pass http://payment-service:3003;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
        }

        # tracking-service
        location /v1/tracking {
            proxy_pass http://tracking-service:3004;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
        }

        # health check
        location /health {
            proxy_pass http://catalog-service:3001;
            proxy_set_header Host $host;
        }
    }
}