events {
    worker_connections 1024;
}

http {
    upstream app_cluster {
        least_conn; # Mengirim traffic ke replica yang koneksinya paling sedikit
        server catalog-service:3001;
        server order-service:3002;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://app_cluster;
            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}